GET  http://localhost:3001/api/apuestas 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZjNkOWI3MjRkMGY0YzM2ZTgwMWE0MiIsInVzZXJuYW1lIjoiVXN1YXJpbyBkZXNkZSBWY29kZSByZXF1ZXN0cyAzIiwiaWF0IjoxNjQzMzcwOTYyLCJleHAiOjE2NDM5NzU3NjJ9.9bc-dufQzMA3q2MUuREtVgTJzKsVI3oDxMIZaX_cBkg
